import { Fragment } from "react"
import Toolbar from "../components/Toolbar"
import '../styles/About/About.css'
import TextBox from "../components/TextBox"
import VerticalLayout from "../components/Layouts/VerticalLayout"
import FlexBox from "../components/Layouts/FlexBox"

const AboutUs = () => {
    return (
        <Fragment>
            <div className="page-container">
                <Toolbar/>
                <VerticalLayout settings={{
                    marginLeft: 10,
                    marginRight: 10,
                    marginTop: 2,
                    marginBottom: 2,
                    innerMargin: 2
                }}>
                    <TextBox 
                        header={'OUR PROJECT'}
                        source={`The Spread of fake media generated by advanced AI techniques in recent years has 
                            been a serious problem in our societies. The tremendous progress of deep learning
                            techniques made it easy to generate quite realistic fake media.
            
                            Our main objective is to detect and prevent the spread of fake videos that can be used 
                            in news, adult content, financial fraud, blackmailing, politics, and more.
                            We use various Image Processing and authentic or manipulated.
                            Our system analyzes the video through four main techniques which tackle different 
                            abnormalities found in manipulated videos which are: Lips movements analysis, 
                            Dynamic Texture analysis, Frequency domain analysis, and finally Self Blending images technique.
            
                            Our system manages to detect fake videos with an accuracy at least 95%, with 
                            providing different analysis insights including the type of manipulation that may have been used.`}/>
                    
                </VerticalLayout>
                
            </div>
        </Fragment>
    )
}

export default AboutUs